export {
  ValueSchemaSchema,
  type ChoiceDomain,
  type Digest,
  type JsonPointer,
  type JsonScalar,
  type JsonValue,
  type PipelineDiagnostic,
  type PipelineDiagnosticFamily,
  type PipelineFailure,
  type ValueSchema,
} from './foundation/index.js';
export {
  PipelineSourcePackageSchema,
  computeSourceDigest,
  definePipelineSource,
  type ActivityRoutes,
  type AgentSlotStrategy,
  type AgentSourceNode,
  type CallSourceNode,
  type ChoiceSourceNode,
  type ConsensusAgentStrategy,
  type ConsensusPolicy,
  type ConsensusRoutes,
  type ConsensusSourceNode,
  type EffectSourceNode,
  type EndSourceNode,
  type ExplicitConsensusParticipant,
  type HumanGateSourceNode,
  type MapSourceNode,
  type ParallelBranchClassification,
  type ParallelPolicy,
  type ParallelRoutes,
  type ParallelSourceBranch,
  type ParallelSourceNode,
  type PipelineSourceModule,
  type PipelineSourcePackage,
  type RegionExitClassification,
  type RepeatCondition,
  type RepeatSourceNode,
  type ScriptSourceNode,
  type SingleAgentStrategy,
  type SourceNode,
  type SourceRegion,
  type SourceRegionExit,
  type ValueMapping,
  type ValueSelector,
  type WaitSourceNode,
} from './source/index.js';
export {
  ProfileMaterializationSchema,
  computeMaterializationDigest,
  defineProfileMaterialization,
  type AbstractParticipant,
  type AgentSlotMaterialization,
  type ProfileMaterialization,
  type SlotSelection,
} from './materialization/index.js';
export {
  PipelineProgramSchema,
  ProgramDigestInputSchema,
  ProgramProvenanceSchema,
  ProgramRequirementsSchema,
  computeProgramDigest,
  type AgentProgramRequirement,
  type EffectProgramRequirement,
  type GenericParallelBranchResult,
  type GenericParallelOutput,
  type LoweringRole,
  type NodeProvenance,
  type PipelineProgram,
  type ProgramActivityNode,
  type ProgramCallNode,
  type ProgramChoiceNode,
  type ProgramDigestInput,
  type ProgramEndNode,
  type ProgramHumanGateNode,
  type ProgramMapNode,
  type ProgramModule,
  type ProgramNode,
  type ProgramNodeId,
  type ProgramParallelBranch,
  type ProgramParallelNode,
  type ProgramProvenance,
  type ProgramRegion,
  type ProgramRegionExit,
  type ProgramRepeatCondition,
  type ProgramRepeatNode,
  type ProgramRequirement,
  type ProgramRequirements,
  type ProgramValueMapping,
  type ProgramValueSelector,
  type ProgramVoteBranch,
  type ProgramWaitNode,
  type RequirementProvenance,
  type ScriptProgramRequirement,
  type VoteParallelBranchResult,
  type VoteParallelOutput,
} from './program/index.js';
export { PipelineCompileResultSchema, type PipelineCompileResult } from './compiler/index.js';
import {
  compilePipeline as compilePipelineInternal,
  type PipelineCompileResult,
} from './compiler/index.js';
import type { ProfileMaterialization } from './materialization/index.js';
import type { PipelineSourcePackage } from './source/index.js';

export const compilePipeline = (
  source: PipelineSourcePackage,
  materialization: ProfileMaterialization,
): PipelineCompileResult => compilePipelineInternal(source, materialization);
